default_sched = "scx_bpfland"
default_mode = "PowerSave"
[scheds.scx_bpfland]
auto_mode = ["-m", "auto", "-f"]
gaming_mode = ["-m", "all", "-f"]
lowlatency_mode = ["-m", "performance", "-w", "-f"]
powersave_mode = ["-s", "20000", "-m", "powersave", "-I", "100", "-t", "100", "-f"]
server_mode = ["-s", "20000", "-S", "-f"]
